APIKEY = '당신의 API key를 입력하세요'
SERVER = 'all'
ALLSERVER = ['cain/', 'diregie/', 'siroco/', 'prey/', 'casillas/', 'hilder/', 'anton/', 'bakal/']
RAW_URL = 'https://dunfamoa.com'
FWLV = 94
DSM = '%eb%8d%98%ec%8b%a0' # Dun sin Maria
MGM = '%eb%a7%90%ea%b1%b8%eb%a9%b4' # Mal girl myun
DGR = '%eb%8b%b9%ea%b7%bc' # Dang geun
AIR = '%ec%97%90%ec%96%b4' # Air
RUV = '%eb%9f%ac%eb%b3%b4' # Ru bow
DAK = '%eb%8b%a4%ec%ba%90' # Da character
EUN = '%ec%9d%80%ed%95%98' # Eun ha
MHY = '%eb%a8%b8%ed%96%90' # Meo hya
DAG = '%eb%8c%80%ea%b5%ac' # Dae gu
CAT = '%ea%b3%a0%ec%96%91' # Go yang yi
TOD = '%ec%98%a4%eb%8a%98' # O neul
LNG = '%eb%a1%b1%ea%b8%b0' # Long gi nus
DNL = '%eb%8d%98%eb%a6%b0' # Dun lin
LIT = 'little' # little
SEA = '%ec%8b%9c%ec%a6%8c' # Season
PSH = 'ParkShinHye' # ParkShinHye
OPT = '%ec%98%b5%ed%8b%b0' # Opti
MOT = 'Mother' # Mother
BYN = '%eb%b3%80' # Byun